### ISSUE TITLE
9.0.1 does not seem to work with bitcoin 0.30

### ISSUE THREAD

**Issue by panicfarm** [rust-bitcoin/rust-miniscript#542]
I get this error with 0.30 (with 0.29 everything works)

```rust
alecm@ark2:~/multisig-test$ cargo watch -x "run --example sighash"
[Running 'cargo run --example sighash']
   Compiling multisig-test v0.1.0 (/home/alecm/multisig-test)
error[E0308]: mismatched types
   --> examples/sighash.rs:229:76
    |
229 |     let ms = Miniscript::<miniscript::bitcoin::PublicKey, Segwitv0>::parse(witness_script).unwrap();
    |              ------------------------------------------------------------- ^^^^^^^^^^^^^^ expected `miniscript::bitcoin::Script`, found `bitcoin::Script`
    |              |
    |              arguments to this function are incorrect
    |
    = note: `bitcoin::Script` and `miniscript::bitcoin::Script` have similar names, but are actually distinct types
note: `bitcoin::Script` is defined in crate `bitcoin`
   --> /home/alecm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-0.30.0/src/blockdata/script/borrowed.rs:72:1
    |
72  | pub struct Script(pub (in crate::blockdata::script) [u8]);
    | ^^^^^^^^^^^^^^^^^
note: `miniscript::bitcoin::Script` is defined in crate `bitcoin`
   --> /home/alecm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-0.29.2/src/blockdata/script.rs:55:1
    |
55  | pub struct Script(Box<[u8]>);
    | ^^^^^^^^^^^^^^^^^
note: associated function defined here
   --> /home/alecm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniscript-9.0.1/src/miniscript/mod.rs:224:12
    |
224 |     pub fn parse(script: &script::Script) -> Result<Miniscript<Ctx::Key, Ctx>, Error> {
    |            ^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `multisig-test` (example "sighash") due to previous error
```

**Comment by apoelstra** [comment]
Yes, there is no expectation that if you use a different major version of a dependency, that the crate will continue to work. This is why cargo will semi-automatically update minor versions, but force you to edit Cargo.toml to change major versions.

One important difference between cargo's "semver" and normal semver is that for 0.x.y, cargo treats x as the "major" and y as the "minor" rev, even though strictly speaking 0 should be the "major" and x the "minor".

**Comment by apoelstra** [comment]
Yes, this library would need to be updated to work with 0.30. The current state of that work is at #537. You could try using the branch from that PR.

**Comment by sanket1729** [comment]
You can try with #537 branch while it is being reviewed.
